name: Update Visitor Counter

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install axios

      - run: node scripts/generate-counter.js

      - name: Push SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: output
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
